apiVersion: v1
kind: Service
metadata:
  name: mssql-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: mssql
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 1433
  type: ClusterIP